declare module 'react-useanimations' {
  import { ComponentClass, HTMLProps, Component } from 'react';

  type Props = HTMLProps<HTMLDivElement> & {
    animationKey:
      | 'activity'
      | 'airplay'
      | 'alertCircle'
      | 'alertOctagon'
      | 'alertTriangle'
      | 'archive'
      | 'arrowDown'
      | 'arrowUp'
      | 'bookmark'
      | 'calendar'
      | 'codepen'
      | 'copy'
      | 'download'
      | 'edit'
      | 'facebook'
      | 'github'
      | 'heart'
      | 'checkbox'
      | 'infinity'
      | 'instagram'
      | 'linkedin'
      | 'loading'
      | 'loading2'
      | 'lock'
      | 'mail'
      | 'maximizeMinimize'
      | 'maximizeMinimize2'
      | 'menu'
      | 'menu2'
      | 'menu3'
      | 'menu4'
      | 'microphone'
      | 'microphone2'
      | 'notification'
      | 'notification2'
      | 'playPause'
      | 'playPauseCircle'
      | 'plusToX'
      | 'pocket'
      | 'radioButton'
      | 'scrollDown'
      | 'searchToX'
      | 'settings'
      | 'settings2'
      | 'skipBack'
      | 'skipForward'
      | 'star'
      | 'toggle'
      | 'trash'
      | 'trash2'
      | 'twitter'
      | 'userMinus'
      | 'userPlus'
      | 'userX'
      | 'video'
      | 'video2'
      | 'visibility'
      | 'visibility2'
      | 'volume';
  };
  // type UseAnimations = Component<Props>;
  class UseAnimations extends React.Component<Props> {}
  export default UseAnimations;
}
